### PR TITLE
Add questions and choices related to no-code/low-code platforms

### PR DESCRIPTION
**Pull request by amine-sahraoui**

### CODE REVIEW

**Comment by aboullaite** [comment]
LGTM.
Wdyt @yjose ?

**Comment by aboullaite** [comment]
Fair enough! Lets start by adding an option to existing questions for no code /low code. If that is proven valuable and popular. We can expand next year

**Comment by amine-sahraoui** [comment]
@yjose sounds good!

**Comment by aboullaite** [comment]
Can you update the PR accordingly

**Comment by amine-sahraoui** [comment]
Done !

**Review by yjose — APPROVED** [review]

**Pull request merged**
