### PR TITLE
Add 2021 and 2022 CSVs and Notebooks

### PR DESCRIPTION
**Pull request by bilalix**
### Changes
* Fixed a bug on the 2020 notebook (commit bddd3a6d43058d47b982ed11f8f09c7e6e2bdadc) and prettify `results.json` file (commit acd2b75)
* Added 2021 CSVs and notebook (commit 5e78deb)
* Add 2022 CSVs and notebook (commit 261166e)

### NB
* Some users (253 to be exact) are empty, they need to be removed (take a look at the `Remove Empty users` section in `results/data/csv/2021_data_processing.ipynb` notebook) -> I'll create an issue for that -> Done (#100 ).
* Same thing regarding 2022 data (367 empty submitters).

### Related issues
* #98

### CODE REVIEW

**Comment by bilalix** [comment]
> Thank you @bilalix for the great work. just one remark, why we need to prettify `results.json` ?

It just makes the file human-readable instead of having one line with a big chunk of text.

We can rename `results_pretty.json` to `results.json` and delete the old `results.json`, I just wanted to check with you guys before doing that.

**Comment by bilalix** [comment]
> @bilalix I dont think its a good idea, we are using `result.json` as an api for the playground screen. i believe prettifying it will increase file size and will make loading the result much slower for the playground.

I see, you have a good point, the main reason why I've done it is because 2021 and 2022 `results.json` files are already prettified.. I can revere the changes back

**Comment by bilalix** [comment]
@yjose I got rid of the file, please feel free to review/merge the changes

**Review by yjose — APPROVED** [review]
Looks good @bilalix . thank you for the great work

**Pull request merged**
